/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.job4j;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello world");
    }
}
